name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
    -
      uses: actions/checkout@master
    - 
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4.7"
    -
      uses: leafo/gh-actions-luarocks@v4
    -
      run: |
        luarocks install luacov
        luarocks install luaunit
    -
      run: |
        ./cli.sh test-self --coverage
    - 
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
